In [1]:
import warnings
warnings.filterwarnings('ignore')

In [2]:
import numpy as np
from qutip import basis,tensor
from qutip.qip import QubitCircuit
from qutip.qip.operations import gate_sequence_product,phasegate,cnot,snot

In [44]:
phasegate(np.pi/2,2,1)*snot(2,1)*phasegate(np.pi/4,2,1)*cnot(2,0,1)*phasegate(np.pi/4,2,1).dag()*snot(2,1)*phasegate(np.pi/2,2,1).dag()

Quantum object: dims = [[2, 2], [2, 2]], shape = (4, 4), type = oper, isherm = True
Qobj data =
[[ 1.          0.          0.          0.        ]
 [ 0.          1.          0.          0.        ]
 [ 0.          0.          0.70710678  0.70710678]
 [ 0.          0.          0.70710678 -0.70710678]]

In [3]:
qc=QubitCircuit(N=2)
qc.add_gate("PHASEGATE",targets=1,arg_value=-np.pi/2)
qc.add_gate("SNOT",targets=1)
qc.add_gate("PHASEGATE",targets=1,arg_value=-np.pi/4)
qc.add_gate("CNOT",targets=1,controls=0)
qc.add_gate("PHASEGATE",targets=1,arg_value=np.pi/4)
qc.add_gate("SNOT",targets=1)
qc.add_gate("PHASEGATE",targets=1,arg_value=np.pi/2)

In [4]:
gate_sequence_product(qc.propagators())

Quantum object: dims = [[2, 2], [2, 2]], shape = (4, 4), type = oper, isherm = True
Qobj data =
[[ 1.          0.          0.          0.        ]
 [ 0.          1.          0.          0.        ]
 [ 0.          0.          0.70710678  0.70710678]
 [ 0.          0.          0.70710678 -0.70710678]]

In [51]:
EC=gate_sequence_product(qc.propagators())*cnot(2,1,0)

In [63]:
EC*tensor([basis(2,1),basis(2,0)])

Quantum object: dims = [[2, 2], [1, 1]], shape = (4, 1), type = ket
Qobj data =
[[0.        ]
 [0.        ]
 [0.70710678]
 [0.70710678]]

In [64]:
EC*tensor([basis(2,0),basis(2,0)])

Quantum object: dims = [[2, 2], [1, 1]], shape = (4, 1), type = ket
Qobj data =
[[1.]
 [0.]
 [0.]
 [0.]]